image: node:alpine
stage:
  - install
  - lint-code
  - build
  - deploy

cache:
  key: vite
  paths:
    - node_modules

job_install: 
  stage: install
  tags: 
    - vite
  script:
    - npm install

job_build:
  stage: build
  tags: 
    - vite
  script:
    - npm run build

job_deploy:
  stage: deploy
  image: docker
  tags: 
    - vite 
  script:
    - docker build -t viteimages .
    - if [ $(docker ps -aq --filter name=myvite-container)];then docker rm -f myvite-container;fi
    - docker run -d -p 80082:80 --name myvite-container viteimages

