job1:
  stage: .pre
  script: 
    - echo 'my pre job1'

job2:
  stage: build
  script: 
    - echo 'my build job2'

job3:
  stage: test
  script: 
    - echo 'my test job3'

job4:
  stage: test
  script: 
    - echo 'my test stage job4'